# fly.toml app configuration file generated for doc2345678645367 on 2025-07-16T09:26:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'doc2345678645367'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
